controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
pdf:
  path: /pdf
  controller: App\Controller\PDFController::generatePdf
search_results:
  path: /search-results
  controller: App\Controller\SearchResultsController::search
  methods: POST
